# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  checklistapi:
    container_name: service
    image: checklist-api
    build:
      context: ./ChecklistAPI
      dockerfile: dockerfile
      args:
        - configuration=Debug
    ports:
      - 5064:5064
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5064
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      # - /ChecklistAPI:/app
    working_dir: /app
    command: ["dotnet", "ChecklistAPI.dll"]

  web:
    container_name: client
    image: shopping-list-client
    build:
      context: ./shopping-list-client
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./shopping-list-client:/app
      - /app/node_modules
    working_dir: /app
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: npm run dev
