# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  db:
    container_name: db
    image: postgres:17
    restart: always
    env_file:
      - ./.env
    ports:
      - 5433:5432
    networks:
      - checklistdb
    volumes:
      - ~/data/pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 20s


  metabase:
    image: metabase/metabase:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3030:3030
    networks:
      - checklistdb

  service:
    container_name: service
    image: checklist-service
    build:
      context: ./service
      dockerfile: dockerfile
      args:
        - configuration=Debug
    ports:
      - 5064:5064
    networks:
      - checklistdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5064
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      # - ./service/bin/Debug/net9.0:/app
    working_dir: /app
    command: ["dotnet", "ChecklistAPI.dll"]

  client:
    container_name: client
    image: checklist-client
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    working_dir: /app
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: npm run dev

# volumes:
#   pgdata:
networks:
  checklistdb:
    driver: bridge
